spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=test
    username: SA
    password: xavierTest123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
  thymeleaf:
    suffix: .html                    # 模板檔案後綴
    encoding: UTF-8                  # 編碼
    cache: false                     # 關閉快取，方便開發時看到即時效果
    mode: HTML5

  web:
    resources:
      add-mappings: true